apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "helm.fullname" . }}
  labels:
    {{- include "helm.labels" . | nindent 4 }}
data:
{{- range $key, $value := .Values.configMapValues }}
  {{ $key }}: "{{ $value }}"
{{- end -}}
