name: Test

# Controls when the workflow will run
on:
  pull_request:
    branches:
      - master

env:
  REGISTRY: docker.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  test:
    runs-on: ubuntu-latest

    steps:
      # Checks-out your repository under $GITHUB_WORKSPACE, so your job can access it
      - uses: actions/checkout@v3
      - name: Use Node.js 18.x
        uses: actions/setup-node@v3
        with:
          node-version: 18.x
          cache: 'npm'
      - name: Install packages
        run: npm install
      - name: Unit tests and Code Coverage
        run: CI=true npm test
      - name: Static Code analysis
        run: npm run lint

  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v3
      - name: Run Snyk SAST (All severity)
        uses: snyk/actions/node@master
        continue-on-error: true
        with:
          command: code test
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Run Snyk SAST
        uses: snyk/actions/node@master
        with:
          command: code test --severity-threshold=high
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/node@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
